// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package queries

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    string
	ExpiresAt time.Time
}

// Sessions. Times are UTC and passed in, so they don't depend on the database
// server's clock or time zone.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (id, username, password_hash, first_name, last_name, timezone)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	FirstName    string
	LastName     string
	Timezone     string
}

// Accounts
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Timezone,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :exec
DELETE FROM sessions WHERE user_id = ? AND token_hash <> ?
`

type DeleteUserSessionsExceptParams struct {
	UserID    string
	TokenHash string
}

func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessionsExcept, arg.UserID, arg.TokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT s.user_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ? AND s.expires_at > ? AND u.deleted_at IS NULL
`

type GetSessionUserParams struct {
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.ExpiresAt)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, first_name, last_name, timezone
FROM users
WHERE id = ? AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           string
	Username     string
	PasswordHash string
	FirstName    string
	LastName     string
	Timezone     string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Timezone,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, first_name, last_name, timezone
FROM users
WHERE username = ? AND deleted_at IS NULL
`

type GetUserByUsernameRow struct {
	ID           string
	Username     string
	PasswordHash string
	FirstName    string
	LastName     string
	Timezone     string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Timezone,
	)
	return i, err
}

const getUserFirstName = `-- name: GetUserFirstName :one
SELECT first_name FROM users WHERE id = ?
`

func (q *Queries) GetUserFirstName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserFirstName, id)
	var first_name string
	err := row.Scan(&first_name)
	return first_name, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET username = ?, first_name = ?, last_name = ?, timezone = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Username  string
	FirstName string
	LastName  string
	Timezone  string
	ID        string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Timezone,
		arg.ID,
	)
	return err
}
