// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgetadmin.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const addBudgetMember = `-- name: AddBudgetMember :exec
INSERT INTO budget_members (user_id, budget_id)
VALUES (?, ?)
`

type AddBudgetMemberParams struct {
	UserID   string
	BudgetID int32
}

func (q *Queries) AddBudgetMember(ctx context.Context, arg AddBudgetMemberParams) error {
	_, err := q.db.ExecContext(ctx, addBudgetMember, arg.UserID, arg.BudgetID)
	return err
}

const createBudget = `-- name: CreateBudget :execresult
INSERT INTO budgets (owner_user_id)
VALUES (?)
`

func (q *Queries) CreateBudget(ctx context.Context, ownerUserID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBudget, ownerUserID)
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = ?
`

func (q *Queries) DeleteBudget(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, id)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, owner_user_id, friend_code, created_at, updated_at
FROM budgets
WHERE id = ?
`

func (q *Queries) GetBudget(ctx context.Context, id int32) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.FriendCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetByFriendCode = `-- name: GetBudgetByFriendCode :one
SELECT id, owner_user_id, friend_code, created_at, updated_at
FROM budgets
WHERE friend_code = ?
`

func (q *Queries) GetBudgetByFriendCode(ctx context.Context, friendCode sql.NullString) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudgetByFriendCode, friendCode)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.FriendCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT m.budget_id, b.owner_user_id
FROM budget_members m
JOIN budgets b ON b.id = m.budget_id
WHERE m.user_id = ?
`

type GetMembershipRow struct {
	BudgetID    int32
	OwnerUserID string
}

func (q *Queries) GetMembership(ctx context.Context, userID string) (GetMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getMembership, userID)
	var i GetMembershipRow
	err := row.Scan(&i.BudgetID, &i.OwnerUserID)
	return i, err
}

const listBudgetMembers = `-- name: ListBudgetMembers :many
SELECT m.user_id, m.joined_at, u.username, u.first_name, u.last_name
FROM budget_members m
JOIN users u ON u.id = m.user_id
WHERE m.budget_id = ?
ORDER BY m.joined_at ASC, m.user_id ASC
`

type ListBudgetMembersRow struct {
	UserID    string
	JoinedAt  time.Time
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) ListBudgetMembers(ctx context.Context, budgetID int32) ([]ListBudgetMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetMembers, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetMembersRow
	for rows.Next() {
		var i ListBudgetMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.JoinedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeBankAccountSettingsForBudget = `-- name: PurgeBankAccountSettingsForBudget :exec
DELETE FROM bank_account_settings WHERE budget_id = ?
`

func (q *Queries) PurgeBankAccountSettingsForBudget(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeBankAccountSettingsForBudget, budgetID)
	return err
}

const purgeBankConnectionForBudget = `-- name: PurgeBankConnectionForBudget :exec
DELETE FROM bank_connections WHERE budget_id = ?
`

func (q *Queries) PurgeBankConnectionForBudget(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeBankConnectionForBudget, budgetID)
	return err
}

const purgeBudgetMembers = `-- name: PurgeBudgetMembers :exec
DELETE FROM budget_members WHERE budget_id = ?
`

func (q *Queries) PurgeBudgetMembers(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeBudgetMembers, budgetID)
	return err
}

const purgeBudgetMonthsForBudget = `-- name: PurgeBudgetMonthsForBudget :exec
DELETE FROM budget_months WHERE budget_id = ?
`

func (q *Queries) PurgeBudgetMonthsForBudget(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeBudgetMonthsForBudget, budgetID)
	return err
}

const purgeCategoryGroupsForBudget = `-- name: PurgeCategoryGroupsForBudget :exec
DELETE FROM category_groups
WHERE budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?)
`

func (q *Queries) PurgeCategoryGroupsForBudget(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeCategoryGroupsForBudget, budgetID)
	return err
}

const purgeExpensesForBudget = `-- name: PurgeExpensesForBudget :exec
DELETE FROM expenses
WHERE budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?)
`

func (q *Queries) PurgeExpensesForBudget(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeExpensesForBudget, budgetID)
	return err
}

const purgeIncomeItemsForBudget = `-- name: PurgeIncomeItemsForBudget :exec
DELETE FROM income_items
WHERE budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?)
`

func (q *Queries) PurgeIncomeItemsForBudget(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, purgeIncomeItemsForBudget, budgetID)
	return err
}

const removeBudgetMember = `-- name: RemoveBudgetMember :execresult
DELETE FROM budget_members
WHERE user_id = ? AND budget_id = ?
`

type RemoveBudgetMemberParams struct {
	UserID   string
	BudgetID int32
}

func (q *Queries) RemoveBudgetMember(ctx context.Context, arg RemoveBudgetMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeBudgetMember, arg.UserID, arg.BudgetID)
}

const updateBudgetFriendCode = `-- name: UpdateBudgetFriendCode :exec
UPDATE budgets SET friend_code = ? WHERE id = ?
`

type UpdateBudgetFriendCodeParams struct {
	FriendCode sql.NullString
	ID         int32
}

func (q *Queries) UpdateBudgetFriendCode(ctx context.Context, arg UpdateBudgetFriendCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateBudgetFriendCode, arg.FriendCode, arg.ID)
	return err
}
