// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countExpensesByMonth = `-- name: CountExpensesByMonth :one
SELECT COUNT(*) FROM expenses
WHERE budget_month_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountExpensesByMonth(ctx context.Context, budgetMonthID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpensesByMonth, budgetMonthID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBudgetMonth = `-- name: CreateBudgetMonth :execresult
INSERT INTO budget_months (budget_id, user_id, month)
VALUES (?, ?, ?)
`

type CreateBudgetMonthParams struct {
	BudgetID int32
	UserID   string
	Month    time.Time
}

func (q *Queries) CreateBudgetMonth(ctx context.Context, arg CreateBudgetMonthParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBudgetMonth, arg.BudgetID, arg.UserID, arg.Month)
}

const createCategoryGroup = `-- name: CreateCategoryGroup :execresult
INSERT INTO category_groups (budget_month_id, name, planned_amount, sort_order, description)
VALUES (?, ?, ?, ?, ?)
`

type CreateCategoryGroupParams struct {
	BudgetMonthID int32
	Name          string
	PlannedAmount string
	SortOrder     int32
	Description   sql.NullString
}

func (q *Queries) CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategoryGroup,
		arg.BudgetMonthID,
		arg.Name,
		arg.PlannedAmount,
		arg.SortOrder,
		arg.Description,
	)
}

const createExpense = `-- name: CreateExpense :execresult
INSERT INTO expenses (budget_month_id, category_group_id, description, amount, transacted_at, note, created_by_user_id, client_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateExpenseParams struct {
	BudgetMonthID   int32
	CategoryGroupID sql.NullInt32
	Description     string
	Amount          string
	TransactedAt    sql.NullTime
	Note            sql.NullString
	CreatedByUserID sql.NullString
	ClientID        sql.NullString
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createExpense,
		arg.BudgetMonthID,
		arg.CategoryGroupID,
		arg.Description,
		arg.Amount,
		arg.TransactedAt,
		arg.Note,
		arg.CreatedByUserID,
		arg.ClientID,
	)
}

const createIncomeItem = `-- name: CreateIncomeItem :execresult
INSERT INTO income_items (budget_month_id, name, planned_amount, received_at, sort_order, created_by_user_id, client_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateIncomeItemParams struct {
	BudgetMonthID   int32
	Name            string
	PlannedAmount   string
	ReceivedAt      sql.NullTime
	SortOrder       int32
	CreatedByUserID sql.NullString
	ClientID        sql.NullString
}

func (q *Queries) CreateIncomeItem(ctx context.Context, arg CreateIncomeItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIncomeItem,
		arg.BudgetMonthID,
		arg.Name,
		arg.PlannedAmount,
		arg.ReceivedAt,
		arg.SortOrder,
		arg.CreatedByUserID,
		arg.ClientID,
	)
}

const deleteCategoryGroup = `-- name: DeleteCategoryGroup :exec
UPDATE category_groups SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeleteCategoryGroup(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryGroup, id)
	return err
}

const deleteExpense = `-- name: DeleteExpense :exec
UPDATE expenses SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeleteExpense(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const deleteIncomeItem = `-- name: DeleteIncomeItem :exec
UPDATE income_items SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) DeleteIncomeItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteIncomeItem, id)
	return err
}

const getBudgetMonth = `-- name: GetBudgetMonth :one
SELECT id, budget_id, user_id, month, created_at, updated_at
FROM budget_months
WHERE budget_id = ? AND month = ? AND deleted_at IS NULL
LIMIT 1
`

type GetBudgetMonthParams struct {
	BudgetID int32
	Month    time.Time
}

type GetBudgetMonthRow struct {
	ID        int32
	BudgetID  int32
	UserID    string
	Month     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetBudgetMonth(ctx context.Context, arg GetBudgetMonthParams) (GetBudgetMonthRow, error) {
	row := q.db.QueryRowContext(ctx, getBudgetMonth, arg.BudgetID, arg.Month)
	var i GetBudgetMonthRow
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.UserID,
		&i.Month,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryGroup = `-- name: GetCategoryGroup :one
SELECT cg.id, cg.budget_month_id, cg.name, cg.planned_amount, cg.sort_order, cg.description, cg.created_at, cg.updated_at
FROM category_groups cg
JOIN budget_months bm ON bm.id = cg.budget_month_id
WHERE cg.id = ? AND bm.budget_id = ? AND cg.deleted_at IS NULL
`

type GetCategoryGroupParams struct {
	ID       int32
	BudgetID int32
}

type GetCategoryGroupRow struct {
	ID            int32
	BudgetMonthID int32
	Name          string
	PlannedAmount string
	SortOrder     int32
	Description   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetCategoryGroup(ctx context.Context, arg GetCategoryGroupParams) (GetCategoryGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryGroup, arg.ID, arg.BudgetID)
	var i GetCategoryGroupRow
	err := row.Scan(
		&i.ID,
		&i.BudgetMonthID,
		&i.Name,
		&i.PlannedAmount,
		&i.SortOrder,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT e.id, e.budget_month_id, e.category_group_id, e.description, e.amount, e.transacted_at, e.note,
       e.external_id, e.source_account_name, e.auto_categorized, e.created_by_user_id, u.first_name AS created_by_name,
       cg.name AS category_name
FROM expenses e
LEFT JOIN users u ON u.id = e.created_by_user_id
LEFT JOIN category_groups cg ON cg.id = e.category_group_id AND cg.deleted_at IS NULL
WHERE e.id = ? AND e.deleted_at IS NULL
`

type GetExpenseRow struct {
	ID                int32
	BudgetMonthID     int32
	CategoryGroupID   sql.NullInt32
	Description       string
	Amount            string
	TransactedAt      sql.NullTime
	Note              sql.NullString
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
	AutoCategorized   bool
	CreatedByUserID   sql.NullString
	CreatedByName     sql.NullString
	CategoryName      sql.NullString
}

func (q *Queries) GetExpense(ctx context.Context, id int32) (GetExpenseRow, error) {
	row := q.db.QueryRowContext(ctx, getExpense, id)
	var i GetExpenseRow
	err := row.Scan(
		&i.ID,
		&i.BudgetMonthID,
		&i.CategoryGroupID,
		&i.Description,
		&i.Amount,
		&i.TransactedAt,
		&i.Note,
		&i.ExternalID,
		&i.SourceAccountName,
		&i.AutoCategorized,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.CategoryName,
	)
	return i, err
}

const getExpenseIDByClientID = `-- name: GetExpenseIDByClientID :one
SELECT id FROM expenses WHERE budget_month_id = ? AND client_id = ? AND deleted_at IS NULL
`

type GetExpenseIDByClientIDParams struct {
	BudgetMonthID int32
	ClientID      sql.NullString
}

func (q *Queries) GetExpenseIDByClientID(ctx context.Context, arg GetExpenseIDByClientIDParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getExpenseIDByClientID, arg.BudgetMonthID, arg.ClientID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getExpenseInBudget = `-- name: GetExpenseInBudget :one

SELECT e.id, e.budget_month_id, e.category_group_id, e.description, e.amount, e.transacted_at, e.note,
       e.external_id, e.source_account_name, e.auto_categorized, e.created_by_user_id, u.first_name AS created_by_name,
       cg.name AS category_name
FROM expenses e
JOIN budget_months bm ON bm.id = e.budget_month_id
LEFT JOIN users u ON u.id = e.created_by_user_id
LEFT JOIN category_groups cg ON cg.id = e.category_group_id AND cg.deleted_at IS NULL
WHERE e.id = ? AND bm.budget_id = ? AND e.deleted_at IS NULL
`

type GetExpenseInBudgetParams struct {
	ID       int32
	BudgetID int32
}

type GetExpenseInBudgetRow struct {
	ID                int32
	BudgetMonthID     int32
	CategoryGroupID   sql.NullInt32
	Description       string
	Amount            string
	TransactedAt      sql.NullTime
	Note              sql.NullString
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
	AutoCategorized   bool
	CreatedByUserID   sql.NullString
	CreatedByName     sql.NullString
	CategoryName      sql.NullString
}

// The categorization worker has no caller, so it reads an expense by ID alone
// (GetExpense above); requests use this one, which stays inside their budget.
func (q *Queries) GetExpenseInBudget(ctx context.Context, arg GetExpenseInBudgetParams) (GetExpenseInBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, getExpenseInBudget, arg.ID, arg.BudgetID)
	var i GetExpenseInBudgetRow
	err := row.Scan(
		&i.ID,
		&i.BudgetMonthID,
		&i.CategoryGroupID,
		&i.Description,
		&i.Amount,
		&i.TransactedAt,
		&i.Note,
		&i.ExternalID,
		&i.SourceAccountName,
		&i.AutoCategorized,
		&i.CreatedByUserID,
		&i.CreatedByName,
		&i.CategoryName,
	)
	return i, err
}

const getIncomeItem = `-- name: GetIncomeItem :one
SELECT ii.id, ii.budget_month_id, ii.name, ii.planned_amount, ii.received_at, ii.sort_order,
       ii.external_id, ii.source_account_name, ii.created_by_user_id, u.first_name AS created_by_name
FROM income_items ii
JOIN budget_months bm ON bm.id = ii.budget_month_id
LEFT JOIN users u ON u.id = ii.created_by_user_id
WHERE ii.id = ? AND bm.budget_id = ? AND ii.deleted_at IS NULL
`

type GetIncomeItemParams struct {
	ID       int32
	BudgetID int32
}

type GetIncomeItemRow struct {
	ID                int32
	BudgetMonthID     int32
	Name              string
	PlannedAmount     string
	ReceivedAt        sql.NullTime
	SortOrder         int32
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
	CreatedByUserID   sql.NullString
	CreatedByName     sql.NullString
}

func (q *Queries) GetIncomeItem(ctx context.Context, arg GetIncomeItemParams) (GetIncomeItemRow, error) {
	row := q.db.QueryRowContext(ctx, getIncomeItem, arg.ID, arg.BudgetID)
	var i GetIncomeItemRow
	err := row.Scan(
		&i.ID,
		&i.BudgetMonthID,
		&i.Name,
		&i.PlannedAmount,
		&i.ReceivedAt,
		&i.SortOrder,
		&i.ExternalID,
		&i.SourceAccountName,
		&i.CreatedByUserID,
		&i.CreatedByName,
	)
	return i, err
}

const getIncomeItemByClientID = `-- name: GetIncomeItemByClientID :one
SELECT id, name, planned_amount, received_at, sort_order
FROM income_items
WHERE budget_month_id = ? AND client_id = ? AND deleted_at IS NULL
`

type GetIncomeItemByClientIDParams struct {
	BudgetMonthID int32
	ClientID      sql.NullString
}

type GetIncomeItemByClientIDRow struct {
	ID            int32
	Name          string
	PlannedAmount string
	ReceivedAt    sql.NullTime
	SortOrder     int32
}

func (q *Queries) GetIncomeItemByClientID(ctx context.Context, arg GetIncomeItemByClientIDParams) (GetIncomeItemByClientIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIncomeItemByClientID, arg.BudgetMonthID, arg.ClientID)
	var i GetIncomeItemByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlannedAmount,
		&i.ReceivedAt,
		&i.SortOrder,
	)
	return i, err
}

const getLatestBudgetMonthBefore = `-- name: GetLatestBudgetMonthBefore :one
SELECT id, budget_id, user_id, month, created_at, updated_at
FROM budget_months
WHERE budget_id = ? AND month < ? AND deleted_at IS NULL
ORDER BY month DESC
LIMIT 1
`

type GetLatestBudgetMonthBeforeParams struct {
	BudgetID int32
	Month    time.Time
}

type GetLatestBudgetMonthBeforeRow struct {
	ID        int32
	BudgetID  int32
	UserID    string
	Month     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetLatestBudgetMonthBefore(ctx context.Context, arg GetLatestBudgetMonthBeforeParams) (GetLatestBudgetMonthBeforeRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestBudgetMonthBefore, arg.BudgetID, arg.Month)
	var i GetLatestBudgetMonthBeforeRow
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.UserID,
		&i.Month,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExpensesByMonth = `-- name: ListAllExpensesByMonth :many
SELECT e.id, e.description, e.amount, e.transacted_at, e.note, e.source_account_name, e.external_id,
       u.first_name AS created_by_name, cg.name AS category_name
FROM expenses e
LEFT JOIN users u ON u.id = e.created_by_user_id
LEFT JOIN category_groups cg ON cg.id = e.category_group_id AND cg.deleted_at IS NULL
WHERE e.budget_month_id = ? AND e.deleted_at IS NULL
ORDER BY (e.transacted_at IS NULL) DESC, e.transacted_at ASC, e.id ASC
`

type ListAllExpensesByMonthRow struct {
	ID                int32
	Description       string
	Amount            string
	TransactedAt      sql.NullTime
	Note              sql.NullString
	SourceAccountName sql.NullString
	ExternalID        sql.NullString
	CreatedByName     sql.NullString
	CategoryName      sql.NullString
}

func (q *Queries) ListAllExpensesByMonth(ctx context.Context, budgetMonthID int32) ([]ListAllExpensesByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllExpensesByMonth, budgetMonthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllExpensesByMonthRow
	for rows.Next() {
		var i ListAllExpensesByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.TransactedAt,
			&i.Note,
			&i.SourceAccountName,
			&i.ExternalID,
			&i.CreatedByName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetMonths = `-- name: ListBudgetMonths :many


SELECT id, budget_id, user_id, month, created_at, updated_at
FROM budget_months
WHERE budget_id = ? AND deleted_at IS NULL
ORDER BY month DESC
`

type ListBudgetMonthsRow struct {
	ID        int32
	BudgetID  int32
	UserID    string
	Month     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Budget months
// Everything is scoped to a budget: a budget is shared by its members, and
// user_id on a month only records who started it. Rows below a month (income,
// categories, expenses) are reached through their month, so the lookups by ID
// also join to it to be sure the row belongs to the caller's budget.
func (q *Queries) ListBudgetMonths(ctx context.Context, budgetID int32) ([]ListBudgetMonthsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetMonths, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetMonthsRow
	for rows.Next() {
		var i ListBudgetMonthsRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.UserID,
			&i.Month,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryGroupsByMonth = `-- name: ListCategoryGroupsByMonth :many

SELECT id, budget_month_id, name, planned_amount, sort_order, description, created_at, updated_at
FROM category_groups
WHERE budget_month_id = ? AND deleted_at IS NULL
ORDER BY sort_order ASC, id ASC
`

type ListCategoryGroupsByMonthRow struct {
	ID            int32
	BudgetMonthID int32
	Name          string
	PlannedAmount string
	SortOrder     int32
	Description   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Category groups
func (q *Queries) ListCategoryGroupsByMonth(ctx context.Context, budgetMonthID int32) ([]ListCategoryGroupsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryGroupsByMonth, budgetMonthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryGroupsByMonthRow
	for rows.Next() {
		var i ListCategoryGroupsByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetMonthID,
			&i.Name,
			&i.PlannedAmount,
			&i.SortOrder,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByMonth = `-- name: ListExpensesByMonth :many

SELECT e.id, e.budget_month_id, e.category_group_id, e.description, e.amount, e.transacted_at, e.note,
       e.external_id, e.source_account_name, e.auto_categorized, e.created_by_user_id, u.first_name AS created_by_name,
       cg.name AS category_name
FROM expenses e
LEFT JOIN users u ON u.id = e.created_by_user_id
LEFT JOIN category_groups cg ON cg.id = e.category_group_id AND cg.deleted_at IS NULL
WHERE e.budget_month_id = ? AND e.deleted_at IS NULL
ORDER BY (e.transacted_at IS NULL) DESC, e.transacted_at DESC, e.id DESC
LIMIT ? OFFSET ?
`

type ListExpensesByMonthParams struct {
	BudgetMonthID int32
	Limit         int64
	Offset        int64
}

type ListExpensesByMonthRow struct {
	ID                int32
	BudgetMonthID     int32
	CategoryGroupID   sql.NullInt32
	Description       string
	Amount            string
	TransactedAt      sql.NullTime
	Note              sql.NullString
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
	AutoCategorized   bool
	CreatedByUserID   sql.NullString
	CreatedByName     sql.NullString
	CategoryName      sql.NullString
}

// Expenses
func (q *Queries) ListExpensesByMonth(ctx context.Context, arg ListExpensesByMonthParams) ([]ListExpensesByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByMonth, arg.BudgetMonthID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByMonthRow
	for rows.Next() {
		var i ListExpensesByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetMonthID,
			&i.CategoryGroupID,
			&i.Description,
			&i.Amount,
			&i.TransactedAt,
			&i.Note,
			&i.ExternalID,
			&i.SourceAccountName,
			&i.AutoCategorized,
			&i.CreatedByUserID,
			&i.CreatedByName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeItemsByMonth = `-- name: ListIncomeItemsByMonth :many

SELECT ii.id, ii.budget_month_id, ii.name, ii.planned_amount, ii.received_at, ii.sort_order,
       ii.external_id, ii.source_account_name, ii.created_by_user_id, u.first_name AS created_by_name
FROM income_items ii
LEFT JOIN users u ON u.id = ii.created_by_user_id
WHERE ii.budget_month_id = ? AND ii.deleted_at IS NULL
ORDER BY ii.sort_order ASC, ii.id ASC
`

type ListIncomeItemsByMonthRow struct {
	ID                int32
	BudgetMonthID     int32
	Name              string
	PlannedAmount     string
	ReceivedAt        sql.NullTime
	SortOrder         int32
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
	CreatedByUserID   sql.NullString
	CreatedByName     sql.NullString
}

// Income items
func (q *Queries) ListIncomeItemsByMonth(ctx context.Context, budgetMonthID int32) ([]ListIncomeItemsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncomeItemsByMonth, budgetMonthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomeItemsByMonthRow
	for rows.Next() {
		var i ListIncomeItemsByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetMonthID,
			&i.Name,
			&i.PlannedAmount,
			&i.ReceivedAt,
			&i.SortOrder,
			&i.ExternalID,
			&i.SourceAccountName,
			&i.CreatedByUserID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedExpenseIDs = `-- name: ListUnassignedExpenseIDs :many
SELECT id FROM expenses
WHERE budget_month_id = ? AND category_group_id IS NULL AND deleted_at IS NULL
ORDER BY id
`

// Every uncategorized expense in a month. Ones the model already declined are
// included: anything uncategorized is worth another try.
func (q *Queries) ListUnassignedExpenseIDs(ctx context.Context, budgetMonthID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedExpenseIDs, budgetMonthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExpenseAutoCategory = `-- name: SetExpenseAutoCategory :execresult
UPDATE expenses SET category_group_id = ?, auto_categorized = 1
WHERE id = ? AND category_group_id IS NULL AND deleted_at IS NULL
`

type SetExpenseAutoCategoryParams struct {
	CategoryGroupID sql.NullInt32
	ID              int32
}

// Never overrides a category a person has already set.
func (q *Queries) SetExpenseAutoCategory(ctx context.Context, arg SetExpenseAutoCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setExpenseAutoCategory, arg.CategoryGroupID, arg.ID)
}

const sumSpentByCategoryGroupForMonth = `-- name: SumSpentByCategoryGroupForMonth :many
SELECT category_group_id, COALESCE(SUM(amount), 0) AS spent
FROM expenses
WHERE budget_month_id = ? AND category_group_id IS NOT NULL AND deleted_at IS NULL
GROUP BY category_group_id
`

type SumSpentByCategoryGroupForMonthRow struct {
	CategoryGroupID sql.NullInt32
	Spent           interface{}
}

func (q *Queries) SumSpentByCategoryGroupForMonth(ctx context.Context, budgetMonthID int32) ([]SumSpentByCategoryGroupForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumSpentByCategoryGroupForMonth, budgetMonthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumSpentByCategoryGroupForMonthRow
	for rows.Next() {
		var i SumSpentByCategoryGroupForMonthRow
		if err := rows.Scan(&i.CategoryGroupID, &i.Spent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSpentForMonth = `-- name: SumSpentForMonth :one
SELECT COALESCE(SUM(amount), 0) AS total_spent
FROM expenses
WHERE budget_month_id = ? AND deleted_at IS NULL
`

func (q *Queries) SumSpentForMonth(ctx context.Context, budgetMonthID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumSpentForMonth, budgetMonthID)
	var total_spent interface{}
	err := row.Scan(&total_spent)
	return total_spent, err
}

const updateCategoryGroup = `-- name: UpdateCategoryGroup :exec
UPDATE category_groups
SET name = ?, planned_amount = ?, sort_order = ?, description = ?
WHERE id = ?
`

type UpdateCategoryGroupParams struct {
	Name          string
	PlannedAmount string
	SortOrder     int32
	Description   sql.NullString
	ID            int32
}

func (q *Queries) UpdateCategoryGroup(ctx context.Context, arg UpdateCategoryGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryGroup,
		arg.Name,
		arg.PlannedAmount,
		arg.SortOrder,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateExpense = `-- name: UpdateExpense :exec
UPDATE expenses
SET category_group_id = ?, description = ?, amount = ?, transacted_at = ?, note = ?, auto_categorized = 0
WHERE id = ?
`

type UpdateExpenseParams struct {
	CategoryGroupID sql.NullInt32
	Description     string
	Amount          string
	TransactedAt    sql.NullTime
	Note            sql.NullString
	ID              int32
}

// Saving an expense is a person confirming it, so it is no longer "automatic".
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error {
	_, err := q.db.ExecContext(ctx, updateExpense,
		arg.CategoryGroupID,
		arg.Description,
		arg.Amount,
		arg.TransactedAt,
		arg.Note,
		arg.ID,
	)
	return err
}

const updateIncomeItem = `-- name: UpdateIncomeItem :exec
UPDATE income_items
SET name = ?, planned_amount = ?, received_at = ?, sort_order = ?
WHERE id = ?
`

type UpdateIncomeItemParams struct {
	Name          string
	PlannedAmount string
	ReceivedAt    sql.NullTime
	SortOrder     int32
	ID            int32
}

func (q *Queries) UpdateIncomeItem(ctx context.Context, arg UpdateIncomeItemParams) error {
	_, err := q.db.ExecContext(ctx, updateIncomeItem,
		arg.Name,
		arg.PlannedAmount,
		arg.ReceivedAt,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
