// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type BankAccount struct {
	ID               int32
	BankConnectionID int32
	ExternalID       string
	Name             string
	OrgName          string
	Currency         string
	Balance          sql.NullString
	BalanceDate      sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type BankAccountSetting struct {
	BudgetID      int32
	ExternalID    string
	Alias         sql.NullString
	InvertAmounts bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BankConnection struct {
	ID           int32
	UserID       string
	BudgetID     int32
	AccessUrl    string
	LastSyncedAt sql.NullTime
	LastError    sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Budget struct {
	ID          int32
	OwnerUserID string
	FriendCode  sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BudgetMember struct {
	UserID   string
	BudgetID int32
	JoinedAt time.Time
}

type BudgetMonth struct {
	ID        int32
	BudgetID  int32
	UserID    string
	Month     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type CategoryGroup struct {
	ID            int32
	BudgetMonthID int32
	Name          string
	PlannedAmount string
	SortOrder     int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	Description   sql.NullString
}

type Expense struct {
	ID                int32
	BudgetMonthID     int32
	CategoryGroupID   sql.NullInt32
	Description       string
	Amount            string
	TransactedAt      sql.NullTime
	Note              sql.NullString
	ExternalID        sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         sql.NullTime
	CreatedByUserID   sql.NullString
	SourceAccountName sql.NullString
	AutoCategorized   bool
	ClientID          sql.NullString
}

type IncomeItem struct {
	ID                int32
	BudgetMonthID     int32
	Name              string
	PlannedAmount     string
	ReceivedAt        sql.NullTime
	ExternalID        sql.NullString
	SortOrder         int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         sql.NullTime
	CreatedByUserID   sql.NullString
	SourceAccountName sql.NullString
	ClientID          sql.NullString
}

type Job struct {
	ID          int32
	Kind        string
	Payload     string
	Attempts    int32
	RunAt       time.Time
	LockedUntil sql.NullTime
	LastError   sql.NullString
	DeadAt      sql.NullTime
	CreatedAt   time.Time
}

type Session struct {
	TokenHash string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	FirstName    string
	LastName     string
	Timezone     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
