// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package queries

import (
	"context"
	"database/sql"
)

const buryJob = `-- name: BuryJob :exec
UPDATE jobs SET dead_at = CURRENT_TIMESTAMP, locked_until = NULL, last_error = ? WHERE id = ?
`

type BuryJobParams struct {
	LastError sql.NullString
	ID        int32
}

// Parks a job that has failed too often.
func (q *Queries) BuryJob(ctx context.Context, arg BuryJobParams) error {
	_, err := q.db.ExecContext(ctx, buryJob, arg.LastError, arg.ID)
	return err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET attempts = attempts + 1, locked_until = datetime('now', CAST(?1 AS TEXT))
WHERE id = (
    SELECT id FROM jobs
    WHERE dead_at IS NULL
      AND run_at <= datetime('now')
      AND (locked_until IS NULL OR locked_until <= datetime('now'))
    ORDER BY run_at, id
    LIMIT 1
)
RETURNING id, kind, payload, attempts
`

type ClaimJobRow struct {
	ID       int32
	Kind     string
	Payload  string
	Attempts int32
}

// Takes the next job that is due and not held by another worker, holding it
// for the lease (an SQLite time modifier such as '+300 seconds'). Times are
// compared using SQLite's own UTC clock, datetime('now').
func (q *Queries) ClaimJob(ctx context.Context, lease string) (ClaimJobRow, error) {
	row := q.db.QueryRowContext(ctx, claimJob, lease)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Attempts,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
DELETE FROM jobs WHERE id = ?
`

func (q *Queries) CompleteJob(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT OR IGNORE INTO jobs (kind, payload) VALUES (?, ?)
`

type EnqueueJobParams struct {
	Kind    string
	Payload string
}

// Queues a job unless the same one is already waiting.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.ExecContext(ctx, enqueueJob, arg.Kind, arg.Payload)
	return err
}

const releaseJob = `-- name: ReleaseJob :exec
UPDATE jobs SET locked_until = NULL, attempts = attempts - 1 WHERE id = ?
`

// Hands back a job the worker gave up on without failing it (it is shutting
// down), so it runs again straight away and the attempt doesn't count.
func (q *Queries) ReleaseJob(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, releaseJob, id)
	return err
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs
SET run_at = datetime('now', CAST(?1 AS TEXT)), locked_until = NULL, last_error = ?2
WHERE id = ?3
`

type RetryJobParams struct {
	Delay     string
	LastError sql.NullString
	ID        int32
}

// Schedules a failed job to run again after the delay (a time modifier, as above).
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.ExecContext(ctx, retryJob, arg.Delay, arg.LastError, arg.ID)
	return err
}
