// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: simplefin.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
)

const budgetMonthSyncedRecently = `-- name: BudgetMonthSyncedRecently :one
SELECT COUNT(*) FROM budget_month_syncs
WHERE budget_month_id = ? AND synced_at > datetime('now', '-15 minutes')
`

// Whether the budget month was successfully synced within the last 15 minutes
// (syncMinInterval in sync.go; keep the two in step). The throttle is per month.
func (q *Queries) BudgetMonthSyncedRecently(ctx context.Context, budgetMonthID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, budgetMonthSyncedRecently, budgetMonthID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearBankConnectionSynced = `-- name: ClearBankConnectionSynced :exec
DELETE FROM budget_month_syncs
WHERE budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?)
`

// Lets the next sync of any month run straight away instead of waiting out the 15 minutes.
func (q *Queries) ClearBankConnectionSynced(ctx context.Context, budgetID int32) error {
	_, err := q.db.ExecContext(ctx, clearBankConnectionSynced, budgetID)
	return err
}

const createExpenseFromSync = `-- name: CreateExpenseFromSync :execresult

INSERT INTO expenses (budget_month_id, category_group_id, description, amount, transacted_at, note, external_id, source_account_name)
VALUES (?, NULL, ?, ?, ?, ?, ?, ?)
ON CONFLICT (budget_month_id, external_id) DO NOTHING
`

type CreateExpenseFromSyncParams struct {
	BudgetMonthID     int32
	Description       string
	Amount            string
	TransactedAt      sql.NullTime
	Note              sql.NullString
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
}

// Sync imports
//
// Both inserts do nothing on a clash with the unique index on external_id, so
// re-syncing a month that was already imported (unique per budget month) silently no-ops for
// transactions we've already seen (RowsAffected() is 0) instead of
// duplicating them.
func (q *Queries) CreateExpenseFromSync(ctx context.Context, arg CreateExpenseFromSyncParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createExpenseFromSync,
		arg.BudgetMonthID,
		arg.Description,
		arg.Amount,
		arg.TransactedAt,
		arg.Note,
		arg.ExternalID,
		arg.SourceAccountName,
	)
}

const createIncomeItemFromSync = `-- name: CreateIncomeItemFromSync :execresult
INSERT INTO income_items (budget_month_id, name, planned_amount, received_at, sort_order, external_id, source_account_name)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (budget_month_id, external_id) DO NOTHING
`

type CreateIncomeItemFromSyncParams struct {
	BudgetMonthID     int32
	Name              string
	PlannedAmount     string
	ReceivedAt        sql.NullTime
	SortOrder         int32
	ExternalID        sql.NullString
	SourceAccountName sql.NullString
}

func (q *Queries) CreateIncomeItemFromSync(ctx context.Context, arg CreateIncomeItemFromSyncParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIncomeItemFromSync,
		arg.BudgetMonthID,
		arg.Name,
		arg.PlannedAmount,
		arg.ReceivedAt,
		arg.SortOrder,
		arg.ExternalID,
		arg.SourceAccountName,
	)
}

const deleteBankAccountsNotIn = `-- name: DeleteBankAccountsNotIn :exec
DELETE FROM bank_accounts
WHERE bank_connection_id = ? AND external_id NOT IN (/*SLICE:external_ids*/?)
`

type DeleteBankAccountsNotInParams struct {
	BankConnectionID int32
	ExternalIds      []string
}

func (q *Queries) DeleteBankAccountsNotIn(ctx context.Context, arg DeleteBankAccountsNotInParams) error {
	query := deleteBankAccountsNotIn
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BankConnectionID)
	if len(arg.ExternalIds) > 0 {
		for _, v := range arg.ExternalIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:external_ids*/?", strings.Repeat(",?", len(arg.ExternalIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:external_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteBankConnectionForBudget = `-- name: DeleteBankConnectionForBudget :execresult
DELETE FROM bank_connections WHERE budget_id = ?
`

// The access URL is a credential, so removing a connection deletes the row
// outright rather than soft-deleting it.
func (q *Queries) DeleteBankConnectionForBudget(ctx context.Context, budgetID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBankConnectionForBudget, budgetID)
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT a.id, a.bank_connection_id, a.external_id, a.name, a.org_name, a.currency, a.balance, a.balance_date,
       s.alias, COALESCE(s.invert_amounts, 0) AS invert_amounts
FROM bank_accounts a
JOIN bank_connections bc ON bc.id = a.bank_connection_id
LEFT JOIN bank_account_settings s ON s.external_id = a.external_id AND s.budget_id = bc.budget_id
WHERE a.id = ? AND bc.budget_id = ?
`

type GetBankAccountParams struct {
	ID       int32
	BudgetID int32
}

type GetBankAccountRow struct {
	ID               int32
	BankConnectionID int32
	ExternalID       string
	Name             string
	OrgName          string
	Currency         string
	Balance          sql.NullString
	BalanceDate      sql.NullTime
	Alias            sql.NullString
	InvertAmounts    bool
}

func (q *Queries) GetBankAccount(ctx context.Context, arg GetBankAccountParams) (GetBankAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getBankAccount, arg.ID, arg.BudgetID)
	var i GetBankAccountRow
	err := row.Scan(
		&i.ID,
		&i.BankConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.OrgName,
		&i.Currency,
		&i.Balance,
		&i.BalanceDate,
		&i.Alias,
		&i.InvertAmounts,
	)
	return i, err
}

const getBankConnectionForBudget = `-- name: GetBankConnectionForBudget :one

SELECT id, user_id, budget_id, access_url, last_synced_at, last_error, created_at, updated_at, deleted_at
FROM bank_connections
WHERE budget_id = ? AND deleted_at IS NULL
`

// Bank connections
//
// Each budget has at most one connection, made when its owner submits a
// SimpleFIN setup token (user_id records who). One access URL covers every
// account linked at the SimpleFIN bridge, and every member of the budget syncs
// through it.
// Column order matches the table so sqlc returns the BankConnection model.
func (q *Queries) GetBankConnectionForBudget(ctx context.Context, budgetID int32) (BankConnection, error) {
	row := q.db.QueryRowContext(ctx, getBankConnectionForBudget, budgetID)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.AccessUrl,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBankAccountSettings = `-- name: ListBankAccountSettings :many

SELECT external_id, alias, invert_amounts FROM bank_account_settings WHERE budget_id = ?
`

type ListBankAccountSettingsRow struct {
	ExternalID    string
	Alias         sql.NullString
	InvertAmounts bool
}

// Account settings
func (q *Queries) ListBankAccountSettings(ctx context.Context, budgetID int32) ([]ListBankAccountSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankAccountSettings, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountSettingsRow
	for rows.Next() {
		var i ListBankAccountSettingsRow
		if err := rows.Scan(&i.ExternalID, &i.Alias, &i.InvertAmounts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT a.id, a.bank_connection_id, a.external_id, a.name, a.org_name, a.currency, a.balance, a.balance_date,
       s.alias, COALESCE(s.invert_amounts, 0) AS invert_amounts
FROM bank_accounts a
JOIN bank_connections bc ON bc.id = a.bank_connection_id
LEFT JOIN bank_account_settings s ON s.external_id = a.external_id AND s.budget_id = bc.budget_id
WHERE a.bank_connection_id = ?
ORDER BY a.org_name, a.name
`

type ListBankAccountsRow struct {
	ID               int32
	BankConnectionID int32
	ExternalID       string
	Name             string
	OrgName          string
	Currency         string
	Balance          sql.NullString
	BalanceDate      sql.NullTime
	Alias            sql.NullString
	InvertAmounts    bool
}

func (q *Queries) ListBankAccounts(ctx context.Context, bankConnectionID int32) ([]ListBankAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBankAccounts, bankConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountsRow
	for rows.Next() {
		var i ListBankAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankConnectionID,
			&i.ExternalID,
			&i.Name,
			&i.OrgName,
			&i.Currency,
			&i.Balance,
			&i.BalanceDate,
			&i.Alias,
			&i.InvertAmounts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBankConnectionFailed = `-- name: MarkBankConnectionFailed :exec
UPDATE bank_connections SET last_error = ? WHERE id = ?
`

type MarkBankConnectionFailedParams struct {
	LastError sql.NullString
	ID        int32
}

func (q *Queries) MarkBankConnectionFailed(ctx context.Context, arg MarkBankConnectionFailedParams) error {
	_, err := q.db.ExecContext(ctx, markBankConnectionFailed, arg.LastError, arg.ID)
	return err
}

const markBudgetMonthSynced = `-- name: MarkBudgetMonthSynced :exec
INSERT INTO budget_month_syncs (budget_month_id, synced_at) VALUES (?, CURRENT_TIMESTAMP)
ON CONFLICT (budget_month_id) DO UPDATE SET synced_at = excluded.synced_at
`

func (q *Queries) MarkBudgetMonthSynced(ctx context.Context, budgetMonthID int32) error {
	_, err := q.db.ExecContext(ctx, markBudgetMonthSynced, budgetMonthID)
	return err
}

const markBankConnectionSynced = `-- name: MarkBankConnectionSynced :exec
UPDATE bank_connections SET last_synced_at = CURRENT_TIMESTAMP, last_error = NULL WHERE id = ?
`

func (q *Queries) MarkBankConnectionSynced(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markBankConnectionSynced, id)
	return err
}

const purgeSyncedExpensesForAccount = `-- name: PurgeSyncedExpensesForAccount :exec

DELETE FROM expenses WHERE external_id LIKE CAST(?1 AS TEXT) || ':%' AND deleted_at IS NULL
  AND budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?2)
`

type PurgeSyncedExpensesForAccountParams struct {
	AccountID string
	BudgetID  int32
}

// Flipping an account's sign makes its imported rows wrong, so they are
// removed outright for the next sync to re-import. Rows the user deleted
// (soft-deleted) are left, so they stay excluded.
func (q *Queries) PurgeSyncedExpensesForAccount(ctx context.Context, arg PurgeSyncedExpensesForAccountParams) error {
	_, err := q.db.ExecContext(ctx, purgeSyncedExpensesForAccount, arg.AccountID, arg.BudgetID)
	return err
}

const purgeSyncedIncomeItemsForAccount = `-- name: PurgeSyncedIncomeItemsForAccount :exec
DELETE FROM income_items WHERE external_id LIKE CAST(?1 AS TEXT) || ':%' AND deleted_at IS NULL
  AND budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?2)
`

type PurgeSyncedIncomeItemsForAccountParams struct {
	AccountID string
	BudgetID  int32
}

func (q *Queries) PurgeSyncedIncomeItemsForAccount(ctx context.Context, arg PurgeSyncedIncomeItemsForAccountParams) error {
	_, err := q.db.ExecContext(ctx, purgeSyncedIncomeItemsForAccount, arg.AccountID, arg.BudgetID)
	return err
}

const removeSyncedExpense = `-- name: RemoveSyncedExpense :exec

UPDATE expenses SET deleted_at = CURRENT_TIMESTAMP
WHERE external_id = ?1 AND deleted_at IS NULL
  AND budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?2)
`

type RemoveSyncedExpenseParams struct {
	ExternalID sql.NullString
	BudgetID   int32
}

// Transfers found after being imported are soft-deleted, which also keeps
// them from being re-imported (external_id stays unique).
func (q *Queries) RemoveSyncedExpense(ctx context.Context, arg RemoveSyncedExpenseParams) error {
	_, err := q.db.ExecContext(ctx, removeSyncedExpense, arg.ExternalID, arg.BudgetID)
	return err
}

const removeSyncedIncomeItem = `-- name: RemoveSyncedIncomeItem :exec
UPDATE income_items SET deleted_at = CURRENT_TIMESTAMP
WHERE external_id = ?1 AND deleted_at IS NULL
  AND budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?2)
`

type RemoveSyncedIncomeItemParams struct {
	ExternalID sql.NullString
	BudgetID   int32
}

func (q *Queries) RemoveSyncedIncomeItem(ctx context.Context, arg RemoveSyncedIncomeItemParams) error {
	_, err := q.db.ExecContext(ctx, removeSyncedIncomeItem, arg.ExternalID, arg.BudgetID)
	return err
}

const renameSyncedExpenses = `-- name: RenameSyncedExpenses :exec

UPDATE expenses SET source_account_name = ?1
WHERE external_id LIKE CAST(?2 AS TEXT) || ':%'
  AND budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?3)
`

type RenameSyncedExpensesParams struct {
	Name      sql.NullString
	AccountID string
	BudgetID  int32
}

// Synced rows have external IDs of the form "<account id>:<transaction id>",
// so an account's rows are found by that prefix.
func (q *Queries) RenameSyncedExpenses(ctx context.Context, arg RenameSyncedExpensesParams) error {
	_, err := q.db.ExecContext(ctx, renameSyncedExpenses, arg.Name, arg.AccountID, arg.BudgetID)
	return err
}

const renameSyncedIncomeItems = `-- name: RenameSyncedIncomeItems :exec
UPDATE income_items SET source_account_name = ?1
WHERE external_id LIKE CAST(?2 AS TEXT) || ':%'
  AND budget_month_id IN (SELECT id FROM budget_months WHERE budget_id = ?3)
`

type RenameSyncedIncomeItemsParams struct {
	Name      sql.NullString
	AccountID string
	BudgetID  int32
}

func (q *Queries) RenameSyncedIncomeItems(ctx context.Context, arg RenameSyncedIncomeItemsParams) error {
	_, err := q.db.ExecContext(ctx, renameSyncedIncomeItems, arg.Name, arg.AccountID, arg.BudgetID)
	return err
}

const upsertBankAccount = `-- name: UpsertBankAccount :exec

INSERT INTO bank_accounts (bank_connection_id, external_id, name, org_name, currency, balance, balance_date)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (bank_connection_id, external_id) DO UPDATE SET
    name = excluded.name,
    org_name = excluded.org_name,
    currency = excluded.currency,
    balance = excluded.balance,
    balance_date = excluded.balance_date
`

type UpsertBankAccountParams struct {
	BankConnectionID int32
	ExternalID       string
	Name             string
	OrgName          string
	Currency         string
	Balance          sql.NullString
	BalanceDate      sql.NullTime
}

// Bank accounts
func (q *Queries) UpsertBankAccount(ctx context.Context, arg UpsertBankAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertBankAccount,
		arg.BankConnectionID,
		arg.ExternalID,
		arg.Name,
		arg.OrgName,
		arg.Currency,
		arg.Balance,
		arg.BalanceDate,
	)
	return err
}

const upsertBankAccountSettings = `-- name: UpsertBankAccountSettings :exec
INSERT INTO bank_account_settings (budget_id, external_id, alias, invert_amounts)
VALUES (?, ?, ?, ?)
ON CONFLICT (budget_id, external_id) DO UPDATE SET alias = excluded.alias, invert_amounts = excluded.invert_amounts
`

type UpsertBankAccountSettingsParams struct {
	BudgetID      int32
	ExternalID    string
	Alias         sql.NullString
	InvertAmounts bool
}

func (q *Queries) UpsertBankAccountSettings(ctx context.Context, arg UpsertBankAccountSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertBankAccountSettings,
		arg.BudgetID,
		arg.ExternalID,
		arg.Alias,
		arg.InvertAmounts,
	)
	return err
}

const upsertBankConnection = `-- name: UpsertBankConnection :exec
INSERT INTO bank_connections (budget_id, user_id, access_url)
VALUES (?, ?, ?)
ON CONFLICT (budget_id) DO UPDATE SET
    user_id = excluded.user_id,
    access_url = excluded.access_url,
    last_error = NULL,
    last_synced_at = NULL
`

type UpsertBankConnectionParams struct {
	BudgetID  int32
	UserID    string
	AccessUrl string
}

// Stores the access URL from a successfully claimed token, replacing any
// earlier connection for the budget.
func (q *Queries) UpsertBankConnection(ctx context.Context, arg UpsertBankConnectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertBankConnection, arg.BudgetID, arg.UserID, arg.AccessUrl)
	return err
}
